import { useRef, useMemo, useEffect, useState } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { Asset } from "./Asset"
import { useConfiguratorStore, pb } from "../store"
import { Suspense } from "react"        

// ------------------------------------------------------------
// extractAvatarElements
// ------------------------------------------------------------
// OLD: generic traversal-based extractor that walked the entire
// glTF scene and collected *all* skinned meshes. This was more
// generic, but also made it harder to reason about which meshes
// and bones belonged to this specific rig, and introduced room
// for mismatch with the animation root.
//
// const extractAvatarElements = (nodes, scene) => {
//   const meshes = []
//   let skeleton = null
//   let hips = null
//
//   scene.traverse((child) => {
//     if (child.isSkinnedMesh) {
//       meshes.push(child)
//       if (!skeleton) skeleton = child.skeleton
//     }
//
//     if (child.isBone && /Hips/i.test(child.name)) {
//       hips = child
//     }
//   })
//
//   return { meshes, skeleton, hips }
// }
//
// NEW: for this specific Drakona rig, we *explicitly* pick out the
// meshes and bones we care about based on node names produced by
// Blender / gltf.pmnd.rs. This matches the auto-generated JSX from
// the viewer, keeps the original hierarchy intact, and guarantees
// that the animation clips find their target bones by name.
const extractAvatarElements = (nodes) => {
  // Main body skinned mesh
  const body = nodes.Body001 ?? nodes.Body ?? null

  // Lower-body clothing skinned mesh
  const bottom = nodes.Bottom ?? null

  // Upper clothing is currently an unskinned mesh in this GLB
  // (gltf.pmnd.rs shows it as <mesh>, not <skinnedMesh>).
  const top = nodes.Top ?? null

  // Skeleton to skin attached assets against: prefer the body's
  // skeleton, otherwise fall back to bottom if needed.
  const skeleton = body?.skeleton ?? bottom?.skeleton ?? null

  // Root bone for the armature. This is what Blender exported as
  // the hip/root and what the animation tracks are targeting:
  // tracks like "Hips001.position", "Back.quaternion", etc.
  const hips = nodes.Hips001 ?? nodes.Hips ?? nodes.mixamorigHips ?? null

  return { body, bottom, top, skeleton, hips }
}

export const Avatar = ({ ...props }) => {
  const group = useRef()

  // Docs for scene and nodes
  // https://github.khronos.org/glTF-Tutorials/gltfTutorial/gltfTutorial_003_MinimalGltfFile.html
  const { nodes, scene, animations } = useGLTF("/models/template_011225_wip_drakona_F.glb")
  const customization = useConfiguratorStore((state) => state.customization)

  // ------------------------------------------------------------
  // Memoized extraction of rig elements
  // ------------------------------------------------------------
  // OLD: generic extractor that returned an array of skinned meshes
  // and we later rendered them with meshes.map(...). This worked,
  // but it meant our R3F tree didn't exactly match the structure
  // the animations were authored for.
  //
  // const { meshes, skeleton, hips } = useMemo(() => {
  //   return extractAvatarElements(nodes, scene)
  // }, [nodes, scene])
  //
  // NEW: use the rig-specific extractor above, which returns the
  // named meshes (body, bottom, top) plus skeleton + hips. This
  // mirrors the JSX generated by gltf.pmnd.rs and ensures the
  // AnimationMixer can find the correct bones by name.
  const { body, bottom, top, skeleton, hips } = useMemo(() => {
    return extractAvatarElements(nodes)
  }, [nodes])

  // ------------------------------------------------------------
  // Animations: useAnimations + manual action map
  // ------------------------------------------------------------
  const { ref, mixer, names, actions: initialActions, clips } = useAnimations(
    animations,
    group
  )
  const currentPose = useConfiguratorStore((state) => state.currentPose)

  // Create a state to hold the actual actions (since useAnimations
  // doesn't create them automatically when we pass a ref manually).
  const [actions, setActions] = useState({})

  // Manually create actions after the ref is attached
  useEffect(() => {
    const createActions = () => {
      if (!group.current || !mixer || !clips || clips.length === 0) return false

      // Create actions for each clip
      const createdActions = {}
      clips.forEach((clip) => {
        const action = mixer.clipAction(clip, group.current)
        createdActions[clip.name] = action
      })

      setActions(createdActions)

      // Verification logging
      console.log("✅ Actions created:", Object.keys(createdActions))
      console.log("✅ Total actions:", Object.keys(createdActions).length)
      console.log("✅ Actions object:", createdActions)

      // Expose to window for debugging
      if (typeof window !== "undefined") {
        window.createdActions = createdActions
      }
      return true
    }

    // Try immediately
    if (!createActions()) {
      // Retry after a short delay if ref isn't ready yet
      const timeout = setTimeout(() => {
        createActions()
      }, 100)
      return () => clearTimeout(timeout)
    }
  }, [mixer, clips])

  // Browser terminal debug
  if (typeof window !== "undefined") {
    window.groupRef = group
    window.useGLTFResult = { nodes, scene, animations }
    window.useAnimationsResult = { ref, mixer, names, actions: initialActions, clips }
    console.log("useGLTF and useAnimation result exposed to window.useGLTFResult", {
      nodes,
      scene,
      animations,
      ref,
      mixer,
      names,
      actions: initialActions,
      clips,
    })
  }

  // ------------------------------------------------------------
  // Switch poses when currentPose changes
  // ------------------------------------------------------------
  useEffect(() => {
    if (!actions || Object.keys(actions).length === 0) return

    // Only play if currentPose is explicitly set (not null/undefined)
    if (currentPose && actions[currentPose]) {
      // Stop everything first
      Object.values(actions).forEach((a) => a.stop())

      // Play the selected pose
      actions[currentPose].reset().play()
      console.log("✅ Playing pose:", currentPose)
    } else {
      // If no pose is selected, stop all animations
      Object.values(actions).forEach((a) => a.stop())
    }
  }, [actions, currentPose])

  // ------------------------------------------------------------
  // JSX: character hierarchy
  // ------------------------------------------------------------
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        {/* We keep an "Armature" wrapper here so you can still scale or
            move the entire character from React without touching the
            underlying skeleton. */}
        <group name="Armature" position={[0, 0, 0]} scale={0.08}>
          {/* Body group roughly mirrors the autogenerated JSX from
              https://gltf.pmnd.rs/ so animation tracks like
              "Hips001.position" still match exactly. */}

          {/* OLD: generic rendering of all skinned meshes. This created
              new SkinnedMesh instances and lost the semantic naming
              (Body001, Bottom, Top) that the animation was authored
              against. It also made it harder to see which mesh was
              which when debugging.
              
              {meshes.map((mesh, i) => (
                <skinnedMesh
                  key={i}
                  geometry={mesh.geometry}
                  material={mesh.material}
                  skeleton={mesh.skeleton}
                  castShadow
                  receiveShadow
                />
              ))}
          */}

          {/* NEW: explicit rig-aware rendering. This is structurally
              equivalent to the JSX from gltf.pmnd.rs, plus comments. */}
          <group name="Body">
            {/* Main body skinned mesh */}
            {body && (
              <skinnedMesh
                name="Body001"
                geometry={body.geometry}
                material={body.material}
                skeleton={body.skeleton}
                castShadow
                receiveShadow
              />
            )}

            {/* Bottom clothing skinned mesh */}
            {bottom && (
              <skinnedMesh
                name="Bottom"
                geometry={bottom.geometry}
                material={bottom.material}
                skeleton={bottom.skeleton}
                castShadow
                receiveShadow
              />
            )}

            {/* Top clothing is currently an unskinned mesh in this GLB.
                If you later skin it in Blender and re-export, this
                would become a <skinnedMesh> using the same skeleton. */}
            {top && (
              <mesh
                name="Top"
                castShadow
                receiveShadow
                geometry={top.geometry}
                material={top.material}
                position={[0, 0.331, 0]} // copied from gltf.pmnd.rs
              />
            )}

            {/* The hips/root bone primitive is what anchors the entire
                skeleton into the scene graph. The animation system
                looks for bones like Hips001, Back, Upperback… under
                this root. */}
            {hips && <primitive object={hips} />}
          </group>

          {/* --------------------------------------------------------
              Customizable attached assets (weapons, armor, etc.)
              These are separate GLBs that load their own geometry +
              material, but they must share the SAME skeleton object
              as the body in order to follow the animation.
             -------------------------------------------------------- */}
          {Object.keys(customization).map((key) => {
            const file =
              customization[key]?.asset &&
              pb.files.getURL(
                customization[key].asset,
                customization[key].asset.url
              )

            return file ? (
              <Suspense key={customization[key].asset.id}>
                <Asset
                  categoryName={key}
                  url={file}
                  // The important part: every attached skinned asset
                  // gets the *same* Skeleton instance as the body,
                  // so all of them deform consistently with the rig.
                  skeleton={skeleton}
                />
              </Suspense>
            ) : null
          })}
        </group>
      </group>
    </group>
  )
}
